"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Loader2, UploadCloud } from "lucide-react";

type AI_Post = {
  title: string;
  content: string;
  type: string;
  category?: string;
};

export default function BulkUploaderClient() {
  const [jsonInput, setJsonInput] = useState("");
  const [isUploading, setIsUploading] = useState(false);
  const [progress, setProgress] = useState({ current: 0, total: 0, successful: 0, failed: 0 });

  const handleUpload = async () => {
    if (!jsonInput.trim()) {
      toast.error("Please paste the JSON output from ChatGPT.");
      return;
    }

    let posts: AI_Post[] = [];
    try {
      posts = JSON.parse(jsonInput);
      if (!Array.isArray(posts)) throw new Error("JSON must be an array of posts");
    } catch (e) {
      toast.error("Invalid JSON format. Make sure it is exactly as ChatGPT outputted it.");
      return;
    }

    if (posts.length === 0) {
      toast.error("No posts found in JSON array.");
      return;
    }

    if (posts.length > 50) {
      toast.error("Please upload a maximum of 50 posts at a time to prevent rate limiting.");
      return;
    }

    setIsUploading(true);
    setProgress({ current: 0, total: posts.length, successful: 0, failed: 0 });

    let successful = 0;
    let failed = 0;

    for (let i = 0; i < posts.length; i++) {
      const post = posts[i];
      setProgress(p => ({ ...p, current: i + 1 }));

      try {
        const res = await fetch("/api/publish", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            title: post.title,
            content: post.content,
            type: post.type || "prose",
            category: post.category || "Uncategorized",
            postTheme: "default",
          }),
        });

        if (res.ok) {
          successful++;
        } else {
          const data = await res.json();
          console.error(`Post ${i + 1} failed:`, data.error);
          failed++;
        }
      } catch (err) {
        console.error(`Post ${i + 1} request error:`, err);
        failed++;
      }

      // Add a small 1-second delay between posts to prevent overwhelming the server
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    setProgress(p => ({ ...p, successful, failed }));
    setIsUploading(false);

    if (failed === 0) {
      toast.success(`Successfully published ${successful} posts!`);
      setJsonInput("");
    } else {
      toast.warning(`Published ${successful} posts, but ${failed} failed. Check console for details.`);
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-12">
      <header className="mb-12">
        <h1 className="text-3xl font-serif text-brand-text mb-4">Bulk AI Uploader</h1>
        <p className="text-brand-soft text-lg">
          Paste the JSON array generated by ChatGPT below. This will instantly publish them to your profile and the public feed.
        </p>
      </header>

      <div className="bg-brand-card border border-brand-border rounded-xl p-6 mb-8">
        <div className="flex justify-between items-center mb-4">
          <label className="text-sm uppercase tracking-widest text-brand-soft font-bold">JSON Input</label>
        </div>
        
        <textarea
          value={jsonInput}
          onChange={(e) => setJsonInput(e.target.value)}
          placeholder={'[\n  {\n    "title": "My Quiet Thought",\n    "content": "<p>Content here...</p>",\n    "type": "prose",\n    "category": "Midnight Thoughts"\n  }\n]'}
          className="w-full h-96 bg-brand-bg/50 border border-brand-border/50 rounded-lg p-4 font-mono text-sm text-brand-text placeholder-brand-soft focus:outline-none focus:border-brand-accent transition-colors"
          disabled={isUploading}
        />

        <div className="mt-8 flex justify-end">
          <button
            onClick={handleUpload}
            disabled={isUploading || !jsonInput.trim()}
            className="flex items-center gap-2 px-8 py-4 bg-brand-text text-brand-bg rounded-full text-sm uppercase tracking-widest font-bold hover:scale-105 transition-transform disabled:opacity-50 disabled:hover:scale-100"
          >
            {isUploading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Publishing ({progress.current}/{progress.total})...
              </>
            ) : (
              <>
                <UploadCloud className="w-5 h-5" />
                Start Bulk Upload
              </>
            )}
          </button>
        </div>
      </div>

      {isUploading && (
        <div className="p-6 bg-brand-accent/10 border border-brand-accent/30 rounded-xl">
          <p className="text-brand-text font-serif mb-2">Upload in progress...</p>
          <div className="w-full bg-brand-border rounded-full h-2 mb-4">
            <div 
              className="bg-brand-accent h-2 rounded-full transition-all duration-300"
              style={{ width: `${(progress.current / progress.total) * 100}%` }}
            />
          </div>
          <div className="flex gap-4 text-sm text-brand-soft">
            <span>Successful: {progress.successful}</span>
            {progress.failed > 0 && <span className="text-red-400">Failed: {progress.failed}</span>}
          </div>
        </div>
      )}
    </div>
  );
}
